before_script:
  - apt-get update -qy
  - apt-get install -y python3-dev python3-pip
  - apt-get install -y pkg-config libhdf5-103 libhdf5-dev
  - pip3 install -r requirements.txt


test_mc:
  stage: test
  script:
    - cd ./NeighborKMC/tutorials/quick/
    - python3 run_quick.py


test_doc:
  stage: test
  script:
    - cd ./documentation/
    - sh build_doc.sh
